fix: Indent of generated code for non-required lists. Thanks @sfowl! (#1050)
The `_transform` macro is called at three different places in this file,
but one location was not similarly indented as the other two. This
caused errors in the ruff post_hook like:

```
error: Failed to parse foo/models/foo_request.py:125:9: Expected an indented block after `if` statement
```

The generated code without the indent fix looks like:

```
        if not isinstance(self.foo, Unset):
        _temp_foo = []  # <-- incorrect indent
            for foo_item_data in self.foo:
                foo_item: Union[None, int]
                foo_item = foo_item_data
                _temp_foo.append(foo_item)
            foo = (None, json.dumps(_temp_foo).encode(), 'application/json')
```

---------

Co-authored-by: Dylan Anthony <43723790+dbanty@users.noreply.github.com>